application: highscores-service
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico|swf))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /googleUser
  script : authentification/google/googleUserEntryPoint.py
  login: required

- url: /facebookCanvas/
  script : authentification/facebook/entryPoint.py

- url: /password
  script : authentification/password/entryPoint.py

- url: /test
  script : authentification/test/entryPoint.py


- url: /cron/updateReviewTimeUnit
  script : cron/updateReviewTimeUnit.py
  login: admin

- url: /cron/clearOldReviewTimeUnitWeights
  script : cron/clearOldReviewTimeUnitWeights.py
  login: admin

- url: /admin/setPlayerAsAdmin
  script : admin/setPlayerAsAdmin.py
  login: admin

- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /amf
  script: amf.py


